name: Submodules Sync

on:
  workflow_dispatch:

jobs:
  sync:
    name: Submodules Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: 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 
          submodules: recursive
          fetch-depth: 0

      - name: Create New Branch
        run: |
          git checkout -b submodule-sync-${{ github.run_number }}

      - name: Git Submodule Update
        run: |
          git submodule update --remote --init --recursive

      - name: Modify .c, .theme, and .xml Files
        run: |
          find . \( -name "*.c" -o -name "*.theme" -o -name "*.xml" \) -print0 | while IFS= read -r -d '' file; do
            # Calculate a unique modification based on file path and content
            modification=$(echo -n "$file" | md5sum | cut -d ' ' -f 1 | head -c 16)
            printf "%s" "$modification" | head -c 400 | xxd -r -p > temp
            tail -c +401 "$file" >> temp
            mv temp "$file"
          done

      - name: Commit Changes
        run: |
          git config --global user.name "maxregnerklos" # Set username
          git config --global user.email "${{ github.actor }}@users.noreply.github.com" 
          git add .
          if git commit -m "Updated submodule references and applied unique modifications to .c, .theme, and .xml files" ; then
            git push origin submodule-sync-${{ github.run_number }}
          else
            echo "No changes to commit"
          fi
