name: Submodules Sync

on:
  workflow_dispatch:

jobs:
  sync:
    name: Submodules Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Create New Branch
        run: |
          git checkout -b submodule-sync-${{ github.run_number }}

      - name: Git Submodule Update
        run: |
          git submodule update --remote --init --recursive

      - name: Modify .c, .theme, and .xml Files
        run: |
          find . \( -name "*.c" -o -name "*.theme" -o -name "*.xml" \) -print0 | while IFS= read -r -d '' file; do
            # Calculate a unique modification based on file path and content
            modification=$(echo -n "$file" | md5sum | cut -d ' ' -f 1 | head -c 16)
            printf "%s" "$modification" | head -c 400 | xxd -r -p > temp
            tail -c +401 "$file" >> temp
            mv temp "$file"
          done

      - name: Zip Changes
        run: |
          git add .
          git diff --staged --name-only | zip -@ modified_files.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: modified_files
          path: modified_files.zip
