name: Submodules Sync

on:
  workflow_dispatch:

jobs:
  sync:
    name: Submodules Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the default GITHUB_TOKEN
          submodules: recursive
          fetch-depth: 0

      - name: Git Submodule Update
        run: |
          git -c protocol.version=2 fetch --prune --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
          git submodule update --remote --init --recursive

      - name: Modify .c, .theme, and .xml Files
        run: |
          find . \( -name "*.c" -o -name "*.theme" -o -name "*.xml" \) -print0 | while IFS= read -r -d '' file; do
            # Calculate a unique modification based on file path and content
            modification=$(echo -n "$file" | md5sum | cut -d ' ' -f 1 | head -c 16)
            printf "%s" "$modification" | head -c 400 | xxd -r -p > temp
            tail -c +401 "$file" >> temp
            mv temp "$file"
          done

      - name: Zip Source Code
        run: zip -r modified_source_code.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: modified_source_code
          path: modified_source_code.zip
